### PR TITLE
Rnatools2

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping  @s-will @eggzilla

**Comment by eggzilla** [comment]
Ok, this means I can add tools to the packages.tsv and everything else happens automatically?

**Comment by bgruening** [comment]
Yes. You will get a minimal Docker container given your conda package as really defined all dependencies.

**Comment by s-will** [comment]
Bjoern, thanks a lot for registering the tools.

I wonder, what is the preferred way to use the quay-dockerized tools
that require file system access.

Something like
docker run -v `pwd`/Examples:/Examples quay.io/mulled/carna:1.3.1--3
carna /Examples/tRNA_2.1.fa /Examples/tRNA_2.2.fa

works well, but is it 'best practice'?

Thanks
S

On 05/04/2016 12:16 AM, Björn Grüning wrote:

> Yes. You will get a minimal Docker container given your conda package as
> really defined all dependencies.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mulled/mulled/pull/53#issuecomment-216681410

## 

Dr. Sebastian Will
Bioinformatics/IZBI
Härtelstrasse 16-18, Room 448.1
University Leipzig
D-04107 Leipzig

Tel.: +49 (0) 341 97 16689

**Comment by bgruening** [comment]
@s-will can you try user-namspaces in Docker. Here is a nice read: https://blog.docker.com/2016/02/docker-engine-1-10-security/

You need to have a recent docker daemon and `--userns-remap` enabled.

**Pull request merged**
