### PR TITLE
Add ddocent

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by thriqon** [comment]
Bash is missing. It is debatable if this is a missing dependency upstream, or if bash should be present in the base image...

**Comment by bgruening** [comment]
@thriqon how large is bash and it's dependencies? Would it be worth to include?

**Comment by bgruening** [comment]
@thriqon there is no bash in conda :(
So I guess this needs to be in the container, otherwise I need to build one. I hope it's not too large.

**Comment by thriqon** [comment]
By reading the installation page for conda I have get the impression that conda somehow requires the presence of bash, which makes this a fault in the mulled. I'll take a look later today, maybe I can get a different base image? Bash is not that big, it's (only) a few MB...

**Comment by bgruening** [comment]
Yes, conda needs bash and can not run with sh. But that a package requires bash is new to me, but also not unexpected.

**Comment by bgruening** [comment]
Already in ...

**Pull request closed without merging**
