### PR TITLE
added cofold

### PR DESCRIPTION
**Pull request by HassanAmr**
Adding cofold package. The package can also be found in bioconda-recipes.

### CODE REVIEW

**Comment by bgruening** [comment]
@thriqon can you look at this? The meta.yaml file is called meta.yaml.tamplate for some unknown reason.

**Comment by thriqon** [comment]
@HassanAmr, could you please change the version number to `2.0.4--1`? Installing Conda packages without the build number is not supported (see #37).

@bgruening, I can't find any file called `meta.yaml.tamplate`...

**Comment by HassanAmr** [comment]
@thriqon, done. Sorry for the oversight.

**Comment by bgruening** [comment]
I'm not sure what is going on with travis. It does not seem to start automatically. I will close and reopen again.

**Comment by bgruening** [comment]
No clue what is going on here.I merged this in https://github.com/mulled/mulled/pull/138
Thanks @HassanAmr!

**Comment by HassanAmr** [comment]
@bgruening, you're welcome. Thanks for your help :)
If there's anything else I should do, please let me know :)

**Comment by bgruening** [comment]
No this was great. Conda, Docker ... the Galaxy wrapper needs maybe an update: https://github.com/bgruening/galaxytools/blob/master/tools/rna_tools/cofold/cofold.xml#L4

But from the dependency side this was it.

Thanks!
Bjoern

**Pull request closed without merging**
